development:
  adapter: postgresql
  encoding: unicode
  database: library_assignment_development
  pool: 5
  username: anthonytroy
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: library_assignment_test
  pool: 5
  username: anthonytroy
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: library_assignment_production
  pool: 5
  username: anthonytroy
  password:

cucumber:
  <<: *test